# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yju8fK_6e7jyWCcLtsSmJNJY0HBqbXMp
"""

!pip install transformers

from transformers import AutoTokenizer ,AutoModelForCausalLM
import torch
import json

model_name = "HuggingFaceTB/SmolLM2-1.7B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

with open("input_prompts.json", "r") as f:
    data = json.load(f)

def direct_prompt(q):
    return f"Q: {q}\nA:"

def instruction_prompt(q):
    return f"Explain the following in a simple way for students:\n{q}"

def few_shot_prompt(q):
    return f"""
Q: What is gravity?
A: Gravity is a force that pulls objects toward each other.

Q: {q}
A:
"""

def generate_text(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        temperature=0.7,
        do_sample=True
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

results = []

for item in data:
    q = item["question"]

    res = {
        "question": q,
        "direct": generate_text(direct_prompt(q)),
        "instruction": generate_text(instruction_prompt(q)),
        "few_shot": generate_text(few_shot_prompt(q))
    }

    results.append(res)

with open("generated_results.json", "w") as f:
    json.dump(results, f, indent=4)

